service:
  port:
    name: http
    l4_protocol: TCP
    port: 8080
    targetPort: 8080
  label: backend-service-1-afoealmgi8
  name: backend-service-1-afoealmgi8
  selector: backend-service-1-afoealmgi8
  type:
  - ClusterIP
  - NodePort
namespace: -@namespace@-
pvc:
  name: pvc-backend-service-1-afoealmgi8
  storageClass: tlc-block-sc
  size: 5Gi
  accessMode: ReadWriteOnce
deployment:
  app:
    name: backend-service-1-afoealmgi8
    type: springboot
  replicas: -@replicas@-
  update:
    type: RollingUpdate
  repo:
    url: -@imageRepoName@-
  image:
    name: backend-service-1-afoealmgi8
    tag: lastest
    secret: -@repoSecret@-
  container:
    name: backend-service-1-afoealmgi8
    port: 8080
  volume:
    name: pvc-backend-service-1-afoealmgi8
  resource:
    request:
      memory: -@requestMemory@-
      cpu: -@requestCpu@-
    limits:
      memory: -@limitsMemory@-
      cpu: -@limitsCpu@-
  backing: 
    mysql:
      name: secret-custom-database-1-06q2ps0ipq
  secret:
    name: []
  configmap:
    name: []
  hpa:
    name: hpa-backend-service-1-afoealmgi8
    minReplicas: -@minReplicas@-
    maxReplicas: -@maxReplicas@-
    cpu: -@cpuAutoScale@-
    memory: -@memAutoScale@-
