service:
  port:
    name: http
    l4_protocol: TCP
    port: 3306
    targetPort: 3306
  label: mysql-service-1-p1aeja49w5
  name: mysql-service-1-p1aeja49w5
  selector: mysql-service-1-p1aeja49w5
  type:
  - ClusterIP
  - NodePort
statefulset:
  name: mysql-service-1-p1aeja49w5
  spec:
    name: mysql-service-1-p1aeja49w5
    servicename: mysql-service-1-p1aeja49w5
  replicas: 1
  container:
    name: mysql-service-1-p1aeja49w5
    port: 3306
  volume:
    name: pvc-mysql-service-1-p1aeja49w5
  resource:
    request:
      memory: 250Mi
      cpu: 0.25
    limits:
      memory: 0Mi
      cpu: 0
  hpa:
    name: hpa-mysql-service-1-p1aeja49w5
    minReplicas: 1
    maxReplicas: 1
    cpu: 70
    memory: -@memAutoScale@-
namespace: testapp-dev
mysql:
  configmap:
    name: config-mysql-service-1-p1aeja49w5
  secret:
    name: secret-mysql-service-1-p1aeja49w5
    username: admin
    password: "Twolinecode12#"
    root_password: "Twolinecode12#"
    database: admin
    dbhost: mysql-service-1-p1aeja49w5
    port: 3306
  statefulset:
    name: mysql-service-1-p1aeja49w5
    image:
      url: registry.turacocloud.com/turaco-common/mysql:8.0.32
secret:
  name: 
  registry:
    name: regsecret
    url: turaco-dev-registry.turacocloud.com/dev-turaco-workspace-268/turaco
    username: robot$turaco_common
    password: Zv7beYWhgCQSOUoxZQK1RGWHdvAMltXx
    email: info@twolinecode.com
pvc:
  name: pvc-mysql-service-1-p1aeja49w5
  storageClass: tlc-block-sc
  size: 5Gi
  accessMode: ReadWriteOnce
